site_name: Datalake Ecommerce — Engenharia de Dados

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Origem dos Dados: origem_dados.md
  - Ingestão (Landing Zone): ingestao_landing.md
  - Transformação:
    - Camada Bronze: bronze.md
    - Camada Silver: silver.md
  - Modelagem Gold:
    - Dimensões (SCD2): dimensoes.md
    - Fato Vendas: fato_vendas.md
    - Regras SCD2: scd2_regras.md
    - Checkpoints (Idempotência): checkpoints.md
  - Visualização:
    - Dashboard e Virtualização: visualizacao.md
  - Referência:
    - Padronização: padronizacao.md
    - Evidências GOLD-10: GOLD_10.md
    - Entrega GOLD-13: GOLD_13.md
